### ISSUE TITLE
singletons-2.3 drops the DemoteRep constructor

### ISSUE THREAD

**Issue by imalsogreg** [k0001/exinst#12]
exinst needs some reworking to support singletons-2.3. (I wonder if it's worth using CPP to support both versions?)

In the singletons changelog:

```
Rework the Sing (a :: *) instance in Data.Singletons.TypeRepStar such that it now uses type-indexed Typeable. The new Sing instance is now:

newtype instance Sing :: Type -> Type where
  STypeRep :: TypeRep a -> Sing a

Accordingly, the SingKind instance has also been changed:

instance SingKind Type where
  type Demote Type = SomeTypeRepStar
  ...

data SomeTypeRepStar where
  SomeTypeRepStar :: forall (a :: *). !(TypeRep a) -> SomeTypeRepStar
```

**Comment by k0001** [comment]
@imalsogreg Hmmm... I think I'm happy to simply drop support for `<2.3`, considering `exinst`'s user-base is rather small and presumably at $company we'll be updating to singletons 2.3 as well.

**Comment by k0001** [comment]
Closing since this has been addressed already. I'll push a release to Hackage soon.
